[package]
name = "maker-panel"
version = "0.1.0"
authors = ["Tom <twitchyliquid64@ciphersink.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
typenum = "1.12"
geo-booleanop = "0.3.2"
geo = "0.16"
usvg = "0.12"
resvg = "0.12"
# gerber-types = { git = "https://github.com/dbrgn/gerber-types-rs", rev = "68c26196d9a2a97e5e29c56c9d7e3d82a52220da" }
# gerber = { git = "https://github.com/dbrgn/gerber-rs", rev = "9260e13e66a7946bad100bf07f2f5975a0f82f69" }
