name: build_wasm
on: [push, pull_request]
jobs:
  native:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta]
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
        targets: "wasm32-unknown-unknown"
    - uses: actions/checkout@master
    - name: Build
      run: |
        cd wasm && \
        cargo build --no-default-features --target wasm32-unknown-unknown
