name: Package
on: [workflow_dispatch]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
    - name: Install cargo-deb
      run: cargo install cargo-deb
    - uses: actions/checkout@master
    - name: Enable Link Time Optimizations
      run: |
        echo "[profile.release]" >> Cargo.toml
        echo "lto = true" >> Cargo.toml
    - run: cargo deb --target=x86_64-unknown-linux-gnu
    - uses: actions/upload-artifact@v2
      with:
        name: maker-panel_amd64.deb
        path: target/**/*_amd64.deb
